apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: user-management
data:
  NODE_ENV: "production"
  PORT: "8000"
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "user_management"
  MONGODB_URI: "mongodb://mongodb-service:27017/user_profiles"

  JWT_EXPIRE: "1h"
  JWT_REFRESH_EXPIRE: "7d"
  BCRYPT_ROUNDS: "12"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  LOG_LEVEL: "info"
  DEFAULT_LANGUAGE: "en"
  SUPPORTED_LANGUAGES: "en,es,fr"